import React from 'react';
import { AlertTriangle, CalendarDays, CheckCircle, Factory } from 'lucide-react';
import moment from 'moment';

function Block({ icon: Icon, title, children }) {
  return <div className="rounded-[24px] p-4 bg-white/65 border border-white shadow-sm"><div className="flex items-center gap-2 mb-3"><Icon className="w-4 h-4 text-orange-600" /><h3 className="font-black text-slate-800">{title}</h3></div><div className="space-y-2">{children}</div></div>;
}

export default function ProductionDailyPanel({ late, today, production, ready }) {
  return <div className="grid grid-cols-1 xl:grid-cols-4 gap-4"><Block icon={AlertTriangle} title="Atrasados">{late.length === 0 && <p className="text-sm text-slate-500">Nenhum atraso.</p>}{late.slice(0, 5).map((o) => <div key={o.id} className="rounded-2xl bg-red-50 border border-red-200 p-3"><p className="font-bold text-slate-800 truncate">{o.client_name}</p><p className="text-xs text-red-700">{o.order_number} · {moment(o.delivery_date).format('DD/MM')}</p></div>)}</Block><Block icon={CalendarDays} title="Entrega hoje">{today.length === 0 && <p className="text-sm text-slate-500">Nada para hoje.</p>}{today.slice(0, 5).map((o) => <div key={o.id} className="rounded-2xl bg-blue-50 border border-blue-200 p-3"><p className="font-bold text-slate-800 truncate">{o.client_name}</p><p className="text-xs text-blue-700">{o.order_number}</p></div>)}</Block><Block icon={Factory} title="Em produção">{production.length === 0 && <p className="text-sm text-slate-500">Fila limpa.</p>}{production.slice(0, 5).map((o) => <div key={o.id} className="rounded-2xl bg-orange-50 border border-orange-200 p-3"><p className="font-bold text-slate-800 truncate">{o.client_name}</p><p className="text-xs text-orange-700">{o.order_number}</p></div>)}</Block><Block icon={CheckCircle} title="Prontos">{ready.length === 0 && <p className="text-sm text-slate-500">Nenhum pronto.</p>}{ready.slice(0, 5).map((o) => <div key={o.id} className="rounded-2xl bg-green-50 border border-green-200 p-3"><p className="font-bold text-slate-800 truncate">{o.client_name}</p><p className="text-xs text-green-700">Aguardando entrega</p></div>)}</Block></div>;
}